#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri May 08 02:02:39 GMT+07:00 2026
maven-metadata-central.xml.error=Could not transfer metadata org.codehaus.mojo/maven-metadata.xml from/to central (https\://repo.maven.apache.org/maven2)\: D\:\\BaitaplonTest\\testweek9\\bai02\\.m2\\repository\\org\\codehaus\\mojo\\maven-metadata-central.xml.2890277347210137306.tmp.8374757951877454634.tmp
maven-metadata-central.xml/@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1778180559443
